CREATE TABLE IF NOT EXISTS urls (
  ID                   LONG          NOT NULL   AUTO_INCREMENT,
  FULL_REFERENCE       VARCHAR(1024) NOT NULL,
  SHORT_REFERENCE      VARCHAR(200)  NOT NULL,
  DATE_OF_CREATION_URL DATE          NOT NULL,
  DATE_OF_ENDING_URL   DATE          NOT NULL,
  IS_ACTIVE            BOOLEAN       NOT NULL,
  IP_ADDRESS           VARCHAR(100)  NOT NULL,
  BROWSER              VARCHAR(2000) NOT NULL,
  PRIMARY KEY (ID));
